# Generated by Django 2.1.1 on 2018-11-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181113_1733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='read_num',
            new_name='ReadNum',
        ),
    ]
