# Generated by Django 2.1.1 on 2018-11-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181113_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-create_time'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
    ]
