# Generated by Django 2.1.3 on 2018-12-13 12:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181203_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='visit_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='博客文章'),
        ),
    ]
