# Generated by Django 2.1.3 on 2019-03-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181213_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='is_lock',
            field=models.CharField(default='2', max_length=32, verbose_name='是否被限制'),
        ),
        migrations.AlterField(
            model_name='userip',
            name='visit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='访问时间'),
        ),
    ]
