# Generated by Django 2.1.3 on 2019-03-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190304_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userip',
            name='is_lock',
        ),
    ]
