# encoding:utf-8
"""
Django settings for work_blog project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from .base import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.environ['SECRET_KEY']
SECRET_KEY = "lls1o)^e+)o+7xrl=h(3c%%=$)y+s7lhs)au%ls)^3-@8ouuv7"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
# DATABASE_PASSWORD = os.environ['DATABASE_PASSWORD']
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'work_blog',
        'HOST': '127.0.0.1',
        'USER': 'root',
        # 'PASSWORD': DATABASE_PASSWORD,
        'PASSWORD': 'ln122920',
        'PORT': 3306,
    }
}

# 配置email发送服务
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.189.cn'              # 邮件服务器
EMAIL_PORT = 25                         # 邮件服务器端口号
EMAIL_HOST_USER = '15639936570@189.cn'  # 邮件用户
# EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']       # 邮件用户密码
EMAIL_SUBJECT_PREFIX = '[大鹏的博客]'     # 邮件主题前缀
EMAIL_USE_TLS = False                   # 是否使用TLS安全传输协议(用于在两个通信应用程序之间提供保密性和数据完整性)