# Generated by Django 2.1.1 on 2018-11-14 12:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('read_statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读数')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '阅读详情',
                'verbose_name_plural': '阅读详情',
            },
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '阅读统计', 'verbose_name_plural': '阅读统计'},
        ),
    ]
